import { createFileRoute } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { NetworkVisual } from "@/components/network-visual";
import { ConsultationFlow } from "@/components/consultation-flow";
import { BackToTop } from "@/components/back-to-top";
import { AccessibilityWidget } from "@/components/accessibility-widget";
import { FaqSection } from "@/components/faq-section";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { AudienceCards } from "@/components/audience-cards";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "ELEVEX | Digital Solutions Development for Growing Businesses" },
    { name: "description", content: "ELEVEX helps growing businesses build better digital experiences, automate processes, implement practical AI solutions and connect the systems they rely on." },
    { property: "og:title", content: "ELEVEX | Digital Solutions Development for Growing Businesses" },
    { property: "og:description", content: "Business-focused digital solutions for better experiences, smarter operations and sustainable growth." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Index,
});

const solutions = [
  { n: "01", title: "Digital Presence", subtitle: "Websites & Digital Experiences", copy: "Build a stronger first impression and turn your website into a real business asset. We create modern, responsive digital experiences designed around your customers and business goals.", addOn: "Brand, graphic design, video & content support available as add-ons.", tags: ["Web Design", "Web Development", "Landing Pages", "Conversion Optimization", "Digital Experiences"], cta: "Explore Digital Solutions →" },
  { n: "02", title: "Automation", subtitle: "Business Process Automation", copy: "Reduce repetitive work and give your team more time to focus on the business. We identify manual processes and connect the tools you already use to create smoother, more efficient workflows.", tags: ["Workflow Automation", "Lead Management", "CRM Automation", "Notifications", "Data Processing", "System Integrations"], cta: "Explore Automation →" },
  { n: "03", title: "AI Solutions", subtitle: "Practical AI for Business", copy: "AI should create measurable value — not just sound impressive. We help businesses identify practical opportunities to use AI to improve productivity, customer experiences and operations.", tags: ["AI Assistants", "AI Workflows", "Customer Support", "Content Automation", "Business Intelligence", "AI Integrations"], cta: "Explore AI Solutions →" },
  { n: "04", title: "Growth Systems", subtitle: "Turn More Opportunities Into Business", copy: "Build systems that help you capture, organize and follow up with potential customers. From lead capture to appointment booking, we connect the digital pieces that help your business grow.", tags: ["Lead Generation Systems", "Qualification Flows", "Appointment Booking", "CRM Integration", "Lead Follow-Up", "Analytics"], cta: "Explore Growth Solutions →" },
];
const values = [["Business First", "We start with your goals, challenges and opportunities — not a predetermined technology stack."], ["Practical Solutions", "We focus on solutions that solve real problems and create measurable value."], ["Built to Scale", "Your business will change. Your digital systems should be ready to change with it."], ["One Digital Partner", "Websites, automation, AI, integrations and growth systems — connected under one partner."]];
const steps = [
  { n: "01", title: "Define Your MVP Requirements", copy: "Spend 2 minutes on our guided MoSCoW discovery form selecting your must-have features, current software stack, and visual style preferences." },
  { n: "02", title: "We Build Your Custom Demo", copy: "Our team reviews your operational bottlenecks and builds a customized front-end visual demo of your future platform within 2–3 business days — entirely free." },
  { n: "03", title: "Review & Fixed Quote", copy: "We send over your custom demo link and invite you to a short video call to walk through the design, map out custom workflows, and lock in a fixed monthly quote." },
  { n: "04", title: "Live Platform in a Week", copy: "We fully program your system, connect your live databases, integrate your tools, and activate your automations or AI assistants, delivering a fully functional live platform.", highlight: true, badge: "Free" },
  { n: "05", title: "Test-Drive Free for 21 Days", copy: "Use your custom platform in real business operations for 21 days with active support. If it drives value, keep it at your quoted rate — otherwise, pay nothing." },
];


const included = ["Hosting and secure infrastructure", "Ongoing maintenance and updates", "Priority support from your team", "Continuous optimization and improvements", "Monitoring, backups and reporting", "Room to add automation and AI over time"];


function Index() {
  return <main id="top" className="overflow-hidden">
    <SiteHeader />
    <section className="relative flex min-h-[88vh] items-center bg-navy pt-20 text-cloud"><NetworkVisual /><div className="absolute inset-0 bg-navy/35" /><div className="relative mx-auto w-full max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="max-w-3xl animate-reveal"><Eyebrow dark>DIGITAL SOLUTIONS DEVELOPMENT</Eyebrow><h1 className="mt-6 text-5xl font-extrabold leading-[1.05] md:text-6xl lg:text-7xl">Test drive your custom digital platform in 7 days.</h1><p className="mt-5 max-w-2xl text-xl font-bold text-cloud/90 md:text-2xl">Transforming Complex Technology into Seamless Growth. — Pay Nothing Until It Works.</p><div className="mt-8 max-w-2xl border-l-2 border-electric pl-6 md:pl-8"><p className="text-xs font-extrabold uppercase tracking-widest text-electric">Our Core Mission</p><p className="mt-4 text-lg leading-relaxed text-cloud/80">At ELEVEX, we empower growing, non-technical small and medium businesses by transforming complex technology into seamless, everyday growth. Through high-performance websites, AI-driven automation, and integrated systems, we eliminate manual operational friction. We handle the technical engineering so you can focus on leading — driving continuous efficiency, sustainable expansion, and compounding output.</p></div><UrgencyBadge dark /><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><a href="#consultation">Request a Custom Demo →</a></Button><Button asChild size="lg" variant="outline" className="border-cloud/30 bg-transparent text-cloud hover:bg-cloud hover:text-navy"><a href="#solutions">Explore Our Solutions</a></Button></div><p className="mt-4 text-sm font-semibold text-cloud/60">A custom demo of your platform, built free — no obligation, no commitment.</p><p className="mt-3 text-sm font-extrabold text-electric">Live platform within a week. Free for 21 days. Pay only if it performs.</p><p className="mt-8 text-xs font-bold uppercase text-cloud/50">Websites&nbsp; • &nbsp;Automation&nbsp; • &nbsp;AI&nbsp; • &nbsp;Integrations&nbsp; • &nbsp;Growth Systems</p></div></div></section>

    <section id="how-we-deliver" className="border-y bg-secondary py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>HOW WE DELIVER</Eyebrow><h2 className="mt-5 text-4xl font-extrabold leading-tight md:text-6xl">From idea to live platform — within a week.</h2><p className="mt-5 max-w-3xl text-lg text-muted-foreground">Every engagement follows the same process, whether it's a new website, an automation build, or a full platform.</p><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-5 lg:items-start">{steps.map((step) => <article key={step.n} className={`relative rounded-md border p-6 ${step.highlight ? "border-primary bg-background shadow-lg md:p-8" : "border-border bg-background"}`}><span className="text-sm font-extrabold text-primary">{step.n}</span>{step.badge && <span className="absolute -top-3 right-4 rounded-full bg-electric px-3 py-1 text-xs font-extrabold text-navy">{step.badge}</span>}<h3 className="mt-4 text-xl font-extrabold">{step.title}</h3><p className="mt-3 text-sm text-muted-foreground">{step.copy}</p></article>)}</div><div className="mt-12 rounded-md bg-navy px-6 py-6 text-center text-lg font-extrabold text-cloud md:text-xl">Try it free for 21 days. Only pay if you keep it.</div></div></section>

    <Section><Eyebrow>YOUR BUSINESS. YOUR TECHNOLOGY.</Eyebrow><div className="mt-6 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><h2 className="text-4xl font-extrabold leading-tight md:text-6xl">Technology should make business easier.</h2><div className="space-y-6 text-lg text-muted-foreground"><p className="font-semibold text-foreground">Too much manual work. Disconnected systems. An outdated website. Missed opportunities. Tools that don't communicate with each other.</p><p>Technology should solve these problems — not create more of them.</p><p>ELEVEX helps businesses identify where technology can make the biggest difference and then builds practical solutions around those opportunities.</p></div></div></Section>
    <section id="solutions" className="bg-background py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>WHAT WE DO</Eyebrow><h2 className="mt-5 max-w-3xl text-4xl font-extrabold leading-tight md:text-6xl">Digital solutions designed around your business.</h2><p className="mt-6 max-w-3xl text-lg text-muted-foreground">Every business is different. That's why we don't sell one-size-fits-all technology. We combine digital development, automation, AI and integrations to create solutions that solve real business problems.</p><div className="mt-14 grid gap-px overflow-hidden rounded-md border bg-border md:grid-cols-2">{solutions.map((item) => <article key={item.n} className="group bg-background p-7 transition-transform hover:-translate-y-1 md:p-10"><span className="text-sm font-extrabold text-primary">{item.n}</span><h3 className="mt-5 text-2xl font-extrabold md:text-3xl">{item.title}</h3><p className="mt-1 text-sm font-semibold text-muted-foreground">{item.subtitle}</p><p className="mt-5 text-muted-foreground">{item.copy}</p>{item.addOn && <p className="mt-4 text-sm font-medium text-primary/80">{item.addOn}</p>}<div className="mt-6 flex flex-wrap gap-2">{item.tags.map((tag) => <span key={tag} className="rounded-sm border px-2.5 py-1 text-xs font-semibold text-muted-foreground">{tag}</span>)}</div><a href="#consultation" className="mt-8 inline-block text-sm font-bold text-primary hover:text-electric">{item.cta}</a></article>)}</div></div></section>
    <section aria-label="Who we work with" className="border-y bg-secondary py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>WHO WE WORK WITH</Eyebrow><h2 className="mt-5 max-w-3xl text-3xl font-extrabold leading-tight md:text-4xl">Built for the businesses we know best.</h2><AudienceCards /></div></section>
    <section id="why" className="bg-navy py-24 text-cloud md:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow dark>WHY ELEVEX</Eyebrow><div className="mt-6 grid gap-8 lg:grid-cols-2"><h2 className="text-4xl font-extrabold md:text-6xl">Technology built around outcomes.</h2><p className="max-w-xl text-lg text-cloud/65">You don't need more technology. You need the right technology. ELEVEX starts with your business objectives and works backward to find the right digital solution.</p></div><div className="mt-16 grid border-y border-cloud/15 md:grid-cols-2 lg:grid-cols-4">{values.map(([title, copy], index) => <div key={title} className={`py-8 md:p-8 ${index > 0 ? "border-t border-cloud/15 md:border-l md:border-t-0" : ""}`}><h3 className="text-xl font-extrabold">{title}</h3><p className="mt-4 text-sm text-cloud/60">{copy}</p></div>)}</div></div></section>
    <section id="pricing" className="py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>SIMPLE, HONEST PRICING</Eyebrow><h2 className="mt-5 max-w-3xl text-4xl font-extrabold leading-tight md:text-6xl">Straightforward pricing. Built around your project.</h2><p className="mt-6 max-w-3xl text-lg text-muted-foreground">Every business starts in a different place, so we scope and price around what you actually need. No packages you'll never use, no surprises later.</p>
      <div className="mt-14 grid gap-8 lg:grid-cols-2">
        <article className="rounded-md border bg-secondary p-8 md:p-10"><span className="text-xs font-extrabold uppercase text-primary">Start here</span><h3 className="mt-4 text-3xl font-extrabold">Free Consultation & Discovery</h3><p className="mt-2 text-4xl font-extrabold text-primary">$0</p><p className="mt-5 text-muted-foreground">A structured 30-minute online video call about your business, your challenges and where technology can make the biggest difference — followed by a clear recommendation and a fixed quote.</p><ul className="mt-6 space-y-3 text-sm">{["No obligation, no commitment", "No card required", "Fixed monthly price quoted on the call", "Live platform delivered within a week", "21 days free before you pay anything"].map((item) => <li key={item} className="flex gap-3"><span aria-hidden="true" className="font-bold text-primary">✓</span><span className="text-muted-foreground">{item}</span></li>)}</ul></article>
        <article className="rounded-md border border-primary bg-background p-8 md:p-10"><span className="text-xs font-extrabold uppercase text-primary">After your free trial</span><h3 className="mt-4 text-3xl font-extrabold">After Your Free Trial</h3><p className="mt-2 text-4xl font-extrabold">From $199<span className="text-lg font-bold text-muted-foreground">/month</span></p><p className="mt-2 text-sm text-muted-foreground">$199 a month covers your core digital presence, hosting and basic CRM integration.</p><ul className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{included.map((item) => <li key={item} className="flex gap-3"><span aria-hidden="true" className="font-bold text-primary">✓</span><span className="text-muted-foreground">{item}</span></li>)}<li className="col-span-full flex gap-3 rounded-md border border-primary/20 bg-primary/5 p-3"><span aria-hidden="true" className="font-bold text-primary">✓</span><span className="font-semibold text-foreground">Custom AI workflows and complex integrations are scoped transparently on your discovery call, so you only pay for the complexity you need.</span></li></ul></article>
      </div>
      <div className="mt-10 flex flex-col items-start gap-3 sm:flex-row sm:items-center"><Button asChild size="lg"><a href="#consultation">Request a Custom Demo →</a></Button><span className="text-sm text-muted-foreground">Most businesses complete the form in under 2 minutes. No sales pressure.</span></div>
    </div></section>
    <section id="consultation" className="py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>REQUEST A CUSTOM DEMO</Eyebrow><p className="mt-3 text-sm font-semibold text-muted-foreground">Tell us what you need and we'll build a custom demo. Prefer email? <a href="mailto:sales@elevex.digital" className="text-primary hover:text-electric">sales@elevex.digital</a> &nbsp;•&nbsp; <a href="https://elevex.digital" className="text-primary hover:text-electric">elevex.digital</a></p><div className="mt-8"><ConsultationFlow /></div></div></section>
    <section className="border-y bg-secondary py-24 md:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Eyebrow>BUILT FOR GROWING BUSINESSES</Eyebrow><div className="mt-5 grid gap-8 lg:grid-cols-[1.4fr_.6fr]"><h2 className="text-4xl font-extrabold leading-tight md:text-6xl">You don't need to be a technology company to use technology better.</h2><p className="text-lg text-muted-foreground">You know your business. We handle the technical complexity, explain decisions clearly, and build systems your team can use with confidence.</p></div></div></section>
    <FaqSection />
    <section className="bg-navy py-24 text-cloud md:py-28"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><Eyebrow dark>READY TO MOVE FORWARD?</Eyebrow><h2 className="mt-5 text-4xl font-extrabold md:text-6xl">Let's build something better.</h2><p className="mx-auto mt-6 max-w-3xl text-lg text-cloud/65">Whether you're looking to modernize your digital presence, automate your operations, implement AI or create a better path to growth, ELEVEX can help you find the right place to start.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg"><a href="#consultation">Request a Custom Demo →</a></Button><Button asChild size="lg" variant="outline" className="border-cloud/30 bg-transparent text-cloud hover:bg-cloud hover:text-navy"><a href="#consultation">Tell Us About Your Business</a></Button></div><p className="mt-5 text-sm text-cloud/60">Prefer email? <a href="mailto:sales@elevex.digital" className="font-semibold text-electric hover:underline">sales@elevex.digital</a></p></div></section>
    <SiteFooter />
    <BackToTop />
    <AccessibilityWidget />
  </main>;
}
function Section({ children }: { children: React.ReactNode }) { return <section className="bg-secondary py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8">{children}</div></section>; }
function Eyebrow({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) { return <p className={`text-xs font-extrabold uppercase ${dark ? "text-electric" : "text-primary"}`}>{children}</p>; }
function UrgencyBadge({ dark = false }: { dark?: boolean }) { return <p className={`mt-7 inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-xs font-bold uppercase tracking-wide ${dark ? "border-electric/40 bg-electric/10 text-electric" : "border-primary/25 bg-primary/5 text-primary"}`}><span className="h-2 w-2 rounded-full bg-electric" />Currently onboarding 15 new builds this quarter</p>; }
