/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as AutomationConsultingRouteImport } from './routes/automation-consulting'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WebsiteDesignRouteImport } from './routes/website-design'
import { Route as ForConsultantsRouteImport } from './routes/for.consultants'
import { Route as ForPropertyManagersRouteImport } from './routes/for.property-managers'
import { Route as ForSecurityRouteImport } from './routes/for.security'
import { Route as ForTradesmenRouteImport } from './routes/for.tradesmen'
import { Route as ForWellnessRouteImport } from './routes/for.wellness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationConsultingRoute = AutomationConsultingRouteImport.update({
  id: '/automation-consulting',
  path: '/automation-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDesignRoute = WebsiteDesignRouteImport.update({
  id: '/website-design',
  path: '/website-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ForConsultantsRoute = ForConsultantsRouteImport.update({
  id: '/for/consultants',
  path: '/for/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPropertyManagersRoute = ForPropertyManagersRouteImport.update({
  id: '/for/property-managers',
  path: '/for/property-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSecurityRoute = ForSecurityRouteImport.update({
  id: '/for/security',
  path: '/for/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTradesmenRoute = ForTradesmenRouteImport.update({
  id: '/for/tradesmen',
  path: '/for/tradesmen',
  getParentRoute: () => rootRouteImport,
} as any)
const ForWellnessRoute = ForWellnessRouteImport.update({
  id: '/for/wellness',
  path: '/for/wellness',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/automation-consulting': typeof AutomationConsultingRoute
  '/blueprints': typeof BlueprintsRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/website-design': typeof WebsiteDesignRoute
  '/for/consultants': typeof ForConsultantsRoute
  '/for/property-managers': typeof ForPropertyManagersRoute
  '/for/security': typeof ForSecurityRoute
  '/for/tradesmen': typeof ForTradesmenRoute
  '/for/wellness': typeof ForWellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/automation-consulting': typeof AutomationConsultingRoute
  '/blueprints': typeof BlueprintsRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/website-design': typeof WebsiteDesignRoute
  '/for/consultants': typeof ForConsultantsRoute
  '/for/property-managers': typeof ForPropertyManagersRoute
  '/for/security': typeof ForSecurityRoute
  '/for/tradesmen': typeof ForTradesmenRoute
  '/for/wellness': typeof ForWellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/automation-consulting': typeof AutomationConsultingRoute
  '/blueprints': typeof BlueprintsRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/website-design': typeof WebsiteDesignRoute
  '/for/consultants': typeof ForConsultantsRoute
  '/for/property-managers': typeof ForPropertyManagersRoute
  '/for/security': typeof ForSecurityRoute
  '/for/tradesmen': typeof ForTradesmenRoute
  '/for/wellness': typeof ForWellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-automation'
    | '/automation-consulting'
    | '/blueprints'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/website-design'
    | '/for/consultants'
    | '/for/property-managers'
    | '/for/security'
    | '/for/tradesmen'
    | '/for/wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-automation'
    | '/automation-consulting'
    | '/blueprints'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/website-design'
    | '/for/consultants'
    | '/for/property-managers'
    | '/for/security'
    | '/for/tradesmen'
    | '/for/wellness'
  id:
    | '__root__'
    | '/'
    | '/ai-automation'
    | '/automation-consulting'
    | '/blueprints'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/website-design'
    | '/for/consultants'
    | '/for/property-managers'
    | '/for/security'
    | '/for/tradesmen'
    | '/for/wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAutomationRoute: typeof AiAutomationRoute
  AutomationConsultingRoute: typeof AutomationConsultingRoute
  BlueprintsRoute: typeof BlueprintsRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  TermsRoute: typeof TermsRoute
  WebsiteDesignRoute: typeof WebsiteDesignRoute
  ForConsultantsRoute: typeof ForConsultantsRoute
  ForPropertyManagersRoute: typeof ForPropertyManagersRoute
  ForSecurityRoute: typeof ForSecurityRoute
  ForTradesmenRoute: typeof ForTradesmenRoute
  ForWellnessRoute: typeof ForWellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-consulting': {
      id: '/automation-consulting'
      path: '/automation-consulting'
      fullPath: '/automation-consulting'
      preLoaderRoute: typeof AutomationConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design': {
      id: '/website-design'
      path: '/website-design'
      fullPath: '/website-design'
      preLoaderRoute: typeof WebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/consultants': {
      id: '/for/consultants'
      path: '/for/consultants'
      fullPath: '/for/consultants'
      preLoaderRoute: typeof ForConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/property-managers': {
      id: '/for/property-managers'
      path: '/for/property-managers'
      fullPath: '/for/property-managers'
      preLoaderRoute: typeof ForPropertyManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/security': {
      id: '/for/security'
      path: '/for/security'
      fullPath: '/for/security'
      preLoaderRoute: typeof ForSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/tradesmen': {
      id: '/for/tradesmen'
      path: '/for/tradesmen'
      fullPath: '/for/tradesmen'
      preLoaderRoute: typeof ForTradesmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/wellness': {
      id: '/for/wellness'
      path: '/for/wellness'
      fullPath: '/for/wellness'
      preLoaderRoute: typeof ForWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAutomationRoute: AiAutomationRoute,
  AutomationConsultingRoute: AutomationConsultingRoute,
  BlueprintsRoute: BlueprintsRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  TermsRoute: TermsRoute,
  WebsiteDesignRoute: WebsiteDesignRoute,
  ForConsultantsRoute: ForConsultantsRoute,
  ForPropertyManagersRoute: ForPropertyManagersRoute,
  ForSecurityRoute: ForSecurityRoute,
  ForTradesmenRoute: ForTradesmenRoute,
  ForWellnessRoute: ForWellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
