/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ForConsultantsRouteImport } from './routes/for.consultants'
import { Route as ForLocalBusinessRouteImport } from './routes/for.local-business'
import { Route as ForSecurityRouteImport } from './routes/for.security'
import { Route as ForTradesmenRouteImport } from './routes/for.tradesmen'
import { Route as ForWellnessRouteImport } from './routes/for.wellness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ForConsultantsRoute = ForConsultantsRouteImport.update({
  id: '/for/consultants',
  path: '/for/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLocalBusinessRoute = ForLocalBusinessRouteImport.update({
  id: '/for/local-business',
  path: '/for/local-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSecurityRoute = ForSecurityRouteImport.update({
  id: '/for/security',
  path: '/for/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTradesmenRoute = ForTradesmenRouteImport.update({
  id: '/for/tradesmen',
  path: '/for/tradesmen',
  getParentRoute: () => rootRouteImport,
} as any)
const ForWellnessRoute = ForWellnessRouteImport.update({
  id: '/for/wellness',
  path: '/for/wellness',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/roadmap': typeof RoadmapRoute
  '/for/consultants': typeof ForConsultantsRoute
  '/for/local-business': typeof ForLocalBusinessRoute
  '/for/security': typeof ForSecurityRoute
  '/for/tradesmen': typeof ForTradesmenRoute
  '/for/wellness': typeof ForWellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/roadmap': typeof RoadmapRoute
  '/for/consultants': typeof ForConsultantsRoute
  '/for/local-business': typeof ForLocalBusinessRoute
  '/for/security': typeof ForSecurityRoute
  '/for/tradesmen': typeof ForTradesmenRoute
  '/for/wellness': typeof ForWellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/roadmap': typeof RoadmapRoute
  '/for/consultants': typeof ForConsultantsRoute
  '/for/local-business': typeof ForLocalBusinessRoute
  '/for/security': typeof ForSecurityRoute
  '/for/tradesmen': typeof ForTradesmenRoute
  '/for/wellness': typeof ForWellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blueprints'
    | '/roadmap'
    | '/for/consultants'
    | '/for/local-business'
    | '/for/security'
    | '/for/tradesmen'
    | '/for/wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blueprints'
    | '/roadmap'
    | '/for/consultants'
    | '/for/local-business'
    | '/for/security'
    | '/for/tradesmen'
    | '/for/wellness'
  id:
    | '__root__'
    | '/'
    | '/blueprints'
    | '/roadmap'
    | '/for/consultants'
    | '/for/local-business'
    | '/for/security'
    | '/for/tradesmen'
    | '/for/wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintsRoute: typeof BlueprintsRoute
  RoadmapRoute: typeof RoadmapRoute
  ForConsultantsRoute: typeof ForConsultantsRoute
  ForLocalBusinessRoute: typeof ForLocalBusinessRoute
  ForSecurityRoute: typeof ForSecurityRoute
  ForTradesmenRoute: typeof ForTradesmenRoute
  ForWellnessRoute: typeof ForWellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/consultants': {
      id: '/for/consultants'
      path: '/for/consultants'
      fullPath: '/for/consultants'
      preLoaderRoute: typeof ForConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/local-business': {
      id: '/for/local-business'
      path: '/for/local-business'
      fullPath: '/for/local-business'
      preLoaderRoute: typeof ForLocalBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/security': {
      id: '/for/security'
      path: '/for/security'
      fullPath: '/for/security'
      preLoaderRoute: typeof ForSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/tradesmen': {
      id: '/for/tradesmen'
      path: '/for/tradesmen'
      fullPath: '/for/tradesmen'
      preLoaderRoute: typeof ForTradesmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/wellness': {
      id: '/for/wellness'
      path: '/for/wellness'
      fullPath: '/for/wellness'
      preLoaderRoute: typeof ForWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintsRoute: BlueprintsRoute,
  RoadmapRoute: RoadmapRoute,
  ForConsultantsRoute: ForConsultantsRoute,
  ForLocalBusinessRoute: ForLocalBusinessRoute,
  ForSecurityRoute: ForSecurityRoute,
  ForTradesmenRoute: ForTradesmenRoute,
  ForWellnessRoute: ForWellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
